"""Addiciona campos para verificacao de email

Revision ID: 13860a35bbab
Revises: 8aef569a3e79
Create Date: 2025-04-19 11:08:02.204853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13860a35bbab'
down_revision = '8aef569a3e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token_verificacao', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_column('token_verificacao')
        batch_op.drop_column('email_verificado')

    # ### end Alembic commands ###
