"""empty message

Revision ID: 63381e58728c
Revises: ca2ff2a27a02
Create Date: 2025-04-17 22:35:29.737097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63381e58728c'
down_revision = 'ca2ff2a27a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
